services:
    _defaults:
        autoconfigure: true
        autowire: true
        bind:
            $projectDir: '%kernel.project_dir%'
            $isDebug: '%kernel.debug%'

    Torr\Hosting\:
        resource: ../src/*
        exclude: ../src/{Exception,AssetsBundle.php}

    Torr\Hosting\Tier\HostingTier:
        $currentTier: !abstract defined via configuration

    Torr\Hosting\Deployment\TaskRunners:
        $postBuildTasks: !tagged_iterator hosting.task.post-build
        $postDeploymentTasks: !tagged_iterator hosting.task.post-deploy

    Torr\Hosting\BuildInfo\BuildInfo:
        $filePath: '%kernel.project_dir%/.build-info.json'

    Torr\Hosting\Deployment\Task\ResetBuildInfoTask:
        tags:
            - name: hosting.task.post-build
              # should run at first
              priority: 10000
