services:
    _defaults:
        autoconfigure: true
        autowire: true
        bind:
            $projectDir: '%kernel.project_dir%'
            $isDebug: '%kernel.debug%'

    Torr\Hosting\:
        resource: ../src/*
        exclude: ../src/{Exception,AssetsBundle.php}

    Torr\Hosting\Tier\HostingTier:
        $currentTier: !abstract defined via configuration

    Torr\Hosting\Deployment\TaskRunners:
        $postBuildTasks: !tagged_iterator 21torr.hosting.post-build
        $postDeploymentTasks: !tagged_iterator 21torr.hosting.post-deploy
