services:
    _defaults:
        autoconfigure: true
        autowire: true
        bind:
            $projectDir: '%kernel.project_dir%'

    Torr\Hosting\:
        resource: ../src/*
        exclude:
            - ../src/BuildInfo/BuildInfo.php
            - ../src/DependencyInjection
            - ../src/Event
            - ../src/Exception
            - ../src/HostingBundle.php

    Torr\Hosting\Hosting\HostingEnvironment:
        $tier: !abstract defined via configuration
        $installationKey: !abstract defined via configuration

    Torr\Hosting\BuildInfo\BuildInfoStorage:
        $filePath: '%kernel.project_dir%/.build-info.json'

    Torr\Hosting\Deployment\Task\ResetBuildInfoTask:
        tags:
            - name: hosting.task.post-build
              # should run at first
              priority: 10000
